services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: perfume-store-api
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - perfume-store-network

  mongodb:
    image: mongo:7
    container_name: perfume-store-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - perfume-store-network

volumes:
  mongodb-data:

networks:
  perfume-store-network:
    driver: bridge
